name: syncio_capstone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.5
  connectivity_plus: ^6.1.0
  equatable: ^2.0.5
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  grpc: ^4.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  protobuf: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2

flutter_native_splash: 
  color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/
    - assets/icon/branding.png
    - assets/images/default_avatar.png
  generate: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
          weight: 400
          style: normal
        - asset: fonts/sf-pro-display/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
          style: normal
        - asset: fonts/sf-pro-display/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYTHINITALIC.OTF
          weight: 100
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYULTRALIGHTITALIC.OTF
          weight: 200
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 700
          style: normal
        - asset: fonts/sf-pro-display/SFPRODISPLAYHEAVYITALIC.OTF
          weight: 800
          style: italic

